"""
Location: paper-a/paper/figaudit.py
Purpose: Run every figure gate over every figure and RECORD the result, pre-rebuild and
         post-rebuild, into out/figures/FIGURE_AUDIT.md. The gates already ran at build time and
         raised on failure; what did not exist was any artifact saying so. A gate that raises
         leaves no evidence it passed, and "we ran the validators" is a claim like any other.
         Usage:  python3 paper/figaudit.py pre|post [--force]
Functions: manual_checks(), run_column(), script_column(), render(), record(), selftest(), main()
Calls: figgate.checks, figcontrast, figclearance, figscript, make_figures.figures
Imports: json, sys, io, contextlib, pathlib, figgate, figcontrast, figclearance, figscript
"""

import contextlib
import io
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import figclearance as FC                                        # noqa: E402
import figcontrast as FK                                         # noqa: E402
import figgate as G                                              # noqa: E402
import figscript as SG                                           # noqa: E402
from figstyle import FS, TEXT_COL                                # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "out" / "figures"
STORE = OUT / "figure_audit.json"
DOC = OUT / "FIGURE_AUDIT.md"
COLUMNS = ("pre", "post")

# The three checks in Part 1c of the brief, which no engine gate performs. Named here so the
# report derives its rows from the same tuple the build gate enforces.
MANUAL = (("1c-1 hatch-on-fill >= 3:1", FK.hatch_violations),
          ("1c-2 error-bar-on-fill >= 3:1", FK.interval_violations),
          ("1c-3 annotation clearance", FC.clearance_violations),
          ("2a greyscale separability", FK.greyscale_violations),
          ("1c-4 label width <= 80% of axis", FC.width_violations))


def manual_checks(fig) -> dict:
    """The manual checks as {label: [violations]}. One call site for the build gate and the audit,
    so a figure cannot ship past a check the report says was run."""
    return {label: fn(fig) for label, fn in MANUAL}


def _result(thunk) -> str:
    """PASS, or FAIL with the validator's own message. The engine's validators print a success
    line to stdout; that is captured so a hundred tick marks do not bury the report."""
    try:
        with contextlib.redirect_stdout(io.StringIO()):
            thunk()
    except Exception as exc:                    # recorded, never swallowed: the record IS the gate
        return f"FAIL::{type(exc).__name__}: {exc}"
    return "PASS"


def run_column() -> dict:
    """Every gate on every figure, as {figure: {gate: result}}. Builds the figures through the
    same roster make_figures ships from, so a figure that is not audited is one that does not
    exist rather than one that was left out of a hand-written list."""
    import matplotlib.pyplot as plt
    import make_figures as MF
    MF.style()
    out = {}
    for _name, fn in MF.figures():
        b = fn()
        row = {label: _result(thunk) for label, thunk in
               G.checks(b.fig, FS, b.concepts, TEXT_COL, b.allow_truncation, b.min_ticks)}
        for label, fn_check in MANUAL:
            hits = fn_check(b.fig)
            row[label] = "PASS" if not hits else "FAIL::" + "; ".join(hits)
        out[b.name] = row
        plt.close(b.fig)
    return out


def script_column() -> dict:
    """validate_mpl_script over every build script. A script that fails it statically has not been
    gated by save(); this paper's builder is one of them, which is why the runtime gates above are
    run explicitly and why the reason is recorded rather than asserted."""
    out = {}
    for path in SG._scripts():
        out[path.name] = _result(lambda p=path: G.engine()["validate_mpl_script"](str(p)))
    return out


def _cell(v: str) -> str:
    return "PASS" if v == "PASS" else "**FAIL**" if v.startswith("FAIL") else "--"


def render(store: dict) -> str:
    """The report. One row per figure per gate, one column per pass, and every failure's message
    reproduced in full below the table -- a table cell cannot hold a validator's message verbatim,
    and paraphrasing it would defeat the point of recording it."""
    figs, notes = {}, []
    for col in COLUMNS:
        for name, row in store.get(col, {}).get("figures", {}).items():
            figs.setdefault(name, {}).update({(k, col): v for k, v in row.items()})
    gates = sorted({k for row in figs.values() for k, _ in row}, key=_order)
    lines = ["# Figure audit", "",
             f"Generated by `paper/figaudit.py`. Columns: {', '.join(COLUMNS)}. "
             "`--` means the column was not recorded.", "",
             "| Figure | Gate | " + " | ".join(COLUMNS) + " |",
             "|---|---|" + "---|" * len(COLUMNS)]
    for name in sorted(figs):
        for gate in gates:
            cells = [_cell(figs[name].get((gate, c), "")) for c in COLUMNS]
            lines.append(f"| `{name}` | {gate} | " + " | ".join(cells) + " |")
            for col in COLUMNS:
                got = figs[name].get((gate, col), "")
                if got.startswith("FAIL::"):
                    notes.append((name, gate, col, got[6:]))
    lines += _script_section(store) + _notes_section(notes)
    return "\n".join(lines) + "\n"


def _order(gate: str) -> tuple:
    return (0 if gate[0] == "G" else 1 if gate.startswith("1c") else 2, gate)


def _script_section(store: dict) -> list:
    """validate_mpl_script, per build script, per column."""
    names = sorted({n for c in COLUMNS for n in store.get(c, {}).get("scripts", {})})
    if not names:
        return []
    out = ["", "## `validate_mpl_script` (static, per build script)", "",
           "| Script | " + " | ".join(COLUMNS) + " |", "|---|" + "---|" * len(COLUMNS)]
    for n in names:
        cells = [_cell(store.get(c, {}).get("scripts", {}).get(n, "")) for c in COLUMNS]
        out.append(f"| `{n}` | " + " | ".join(cells) + " |")
    return out


def _notes_section(notes: list) -> list:
    if not notes:
        return ["", "## Verbatim messages", "", "No gate failed in any recorded column."]
    out = ["", "## Verbatim messages", ""]
    for name, gate, col, msg in notes:
        out += [f"**`{name}` -- {gate} -- {col}**", "", "```", msg.rstrip(), "```", ""]
    return out


def record(column: str, force: bool = False) -> str:
    """Write one column and regenerate the report from BOTH.

    The store is read before it is written and the other column is carried forward untouched; a
    recorded pre-rebuild column is evidence, and a generator that rewrote the file from the run in
    front of it would destroy exactly the record this module exists to produce. Re-recording an
    existing column needs --force, so it cannot happen by running the command twice."""
    if column not in COLUMNS:
        raise SystemExit(f"column must be one of {COLUMNS}, got {column!r}")
    OUT.mkdir(parents=True, exist_ok=True)
    store = json.loads(STORE.read_text()) if STORE.exists() else {}
    if column in store and not force:
        raise SystemExit(f"{column!r} is already recorded in {STORE.name}; pass --force to "
                         "overwrite it, or record the other column")
    store[column] = {"figures": run_column(), "scripts": script_column()}
    STORE.write_text(json.dumps(store, indent=1, sort_keys=True) + "\n")
    DOC.write_text(render(store))
    fails = sum(1 for row in store[column]["figures"].values()
                for v in row.values() if v.startswith("FAIL"))
    cells = sum(len(row) for row in store[column]["figures"].values())
    return (f"figaudit: recorded {column!r} -- {cells - fails}/{cells} figure-gate cells PASS, "
            f"{fails} FAIL; {DOC.relative_to(ROOT)} regenerated from "
            f"{sorted(set(store) & set(COLUMNS))}")


def selftest() -> str:
    """The renderer must show a failure as a failure and reproduce its message, and must not lose
    a column it did not run. Driven on a fixture, so it needs no figures."""
    store = {"pre": {"figures": {"f.pdf": {"G4 x": "FAIL::ValueError: bad\ncolour"}}, "scripts": {}},
             "post": {"figures": {"f.pdf": {"G4 x": "PASS"}}, "scripts": {"s.py": "PASS"}}}
    md = render(store)
    assert "| `f.pdf` | G4 x | **FAIL** | PASS |" in md, f"both columns must appear:\n{md}"
    assert "ValueError: bad\ncolour" in md, "the message must be reproduced verbatim, newline "\
                                            "and all"
    assert "| `s.py` | -- | PASS |" in md, "a script recorded in one column only must show --"
    solo = render({"pre": {"figures": {"f.pdf": {"G4 x": "PASS"}}, "scripts": {}}})
    assert "No gate failed" in solo, "a clean store must say so rather than print an empty section"
    assert "PASS | -- |" in solo, "and the unrecorded column must read -- , never PASS"
    return ("figaudit selftest PASS - the report carries both columns, marks a failure as FAIL, "
            "reproduces its message verbatim including newlines, and never renders an unrecorded "
            "column as a pass")


def main() -> None:
    args = sys.argv[1:]
    if not args or args[0] == "selftest":
        print(selftest())
        return
    print(record(args[0], "--force" in args))


if __name__ == "__main__":
    main()
